@startuml
title TCP Handshake
scale 2.5
skinparam NoteFontSize 6
skinparam NoteShadowing true
skinparam ArrowFontSize 9
participant Client
participant Server
autonumber
Client -> Server: SYN
note left: send SYN (seq=x)
note right: receive SYN(seq=x)
Server --> Client: SYN/ACK
note left: receive SYN (seq=y, ACK=x+1)
note right: send SYN (seq=y, ACK=x+1)
Client -> Server: ACK
note left: send ACK (ack=y+1)
note right: receive ACK (ack=y+1)
@enduml